---
name: 'Test PR'
on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch Name to Test From'
        required: true
      extra_args:
        description: 'Additional Arguments to for run_kontro.sh '
        required: false

# Multiple Runs will need to be allowed to queue
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sanity-check:
    name: 'Optimism Kontrol CI'
    runs-on: [self-hosted, linux, prover]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          fetch-depth: 0 
          submodules: 'recursive'
          
      - name: "Checkout Optimism"
        uses: actions/checkout@v4
        with:
          repository: 'ethereum-optimism/optimism'
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          path: 'optimism'
          ref: ${{ github.event.inputs.branch_name }}
          fetch-depth: 0
          submodules: 'recursive'
 
      - name: 'Run Kontrol'
        shell: bash
        run: |
          # Run the following in the running docker container
          pushd optimism > /dev/null
          find . -name "run-kontrol.sh" -type f -exec {} ${{ github.event.inputs.extra_args }} \;
          
      - name: 'Upload results.tar.gz'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Kontrol Results
          path: kontrol-results_latest.tar.gz
          retention-days: 5